import type { Metadata } from "next";
import "./globals.css";
import UIWrapper from "@/components/layout/UIWrapper";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
	title: "Ceater Buster Clone",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AuthProvider>
					<UIWrapper>{children}</UIWrapper>
				</AuthProvider>
			</body>
		</html>
	);
}
